export default function Footer() {
  return (
    <footer className="border-t border-gray-100 bg-gray-50/50 py-6 text-center text-xs text-gray-400">
      <div className="flex flex-col sm:flex-row items-center justify-between px-8 gap-2">
        <p>&copy; {new Date().getFullYear()} Avery&apos;s Household. All rights reserved.</p>
        <p className="italic font-medium">Generated by Eat at Home LLC</p>
      </div>
    </footer>
  );
}
